version: "3.8"

services:
  backend:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
